import { Button } from "@/components/ui/button";
import { ChevronDown, Filter, RotateCcw } from "lucide-react";
import React, { type ReactNode } from "react";

export type DashboardDateFilters = { startDate?: string; endDate?: string };

export function DashboardSelect({ value, onChange, children, ariaLabel }: { value: string; onChange: (value: string) => void; children: ReactNode; ariaLabel: string }) {
  return <label className="relative block"><select aria-label={ariaLabel} value={value} onChange={event => onChange(event.target.value)} className="h-8 appearance-none rounded-lg border border-border bg-background py-0 pl-2.5 pr-7 text-[11px] font-medium text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15">{children}</select><ChevronDown className="pointer-events-none absolute right-2 top-1/2 size-3 -translate-y-1/2 text-muted-foreground" /></label>;
}

export function DashboardFilterControls({ filters, periodPreset, onDateChange, onPresetChange, onReset }: { filters: DashboardDateFilters; periodPreset: string; onDateChange: (field: "startDate" | "endDate", value: string) => void; onPresetChange: (value: string) => void; onReset: () => void }) {
  return <><div className="grid gap-3 rounded-2xl border bg-background/65 p-4 lg:grid-cols-[auto_1fr_1fr_auto]"><div className="flex items-center gap-2 text-sm font-semibold"><Filter className="size-4 text-primary" />Filtros globais</div><label className="grid gap-1 text-[11px] font-medium text-muted-foreground">Data inicial<input aria-label="Data inicial" type="date" value={filters.startDate ?? ""} max={filters.endDate ?? undefined} onChange={event => onDateChange("startDate", event.target.value)} className="h-9 rounded-lg border bg-background px-2.5 text-sm text-foreground outline-none focus:border-primary" /></label><label className="grid gap-1 text-[11px] font-medium text-muted-foreground">Data final<input aria-label="Data final" type="date" value={filters.endDate ?? ""} min={filters.startDate ?? undefined} onChange={event => onDateChange("endDate", event.target.value)} className="h-9 rounded-lg border bg-background px-2.5 text-sm text-foreground outline-none focus:border-primary" /></label><div className="grid gap-1 text-[11px] font-medium text-muted-foreground">Período<DashboardSelect ariaLabel="Período pré-definido" value={periodPreset} onChange={onPresetChange}><option value="all">Todo o período</option><option value="7">Próximos 7 dias</option><option value="30">Próximos 30 dias</option><option value="custom">Personalizado</option></DashboardSelect></div></div>{(filters.startDate || filters.endDate) && <div className="flex justify-end"><Button variant="ghost" size="sm" className="h-7 text-xs text-muted-foreground" onClick={onReset}><RotateCcw className="mr-1.5 size-3.5" />Limpar filtros</Button></div>}</>;
}
