import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { DashboardFilterControls, DashboardSelect } from "@/components/DashboardControls";
import { filterMacroCategoryByDay } from "@/lib/dashboardFilters";
import { futurePeriodFromSelectedStart } from "@/lib/dashboardPeriod";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Boxes, CalendarDays, PackageCheck, RefreshCw, Truck } from "lucide-react";
import React, { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, LabelList, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type ChartPoint = { label: string; value: number };
type MacroCategoryDayPoint = ChartPoint & { date: string; macroCategory: string };
type DashboardFilters = { startDate?: string; endDate?: string };

const formatNumber = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 0 });
const seriesColors = ["#2563eb", "#0ea5e9", "#14b8a6", "#8b5cf6", "#f59e0b", "#ec4899", "#64748b"];

function EmptyChart() { return <div className="flex h-[280px] flex-col items-center justify-center text-center"><CalendarDays className="mb-3 size-7 text-muted-foreground/60" /><p className="text-sm font-medium">Sem dados para esta visão</p><p className="mt-1 max-w-56 text-xs leading-5 text-muted-foreground">Ajuste os filtros ou importe uma programação de agenda.</p></div>; }
function ChartCard({ title, description, data, actions, children, className = "" }: { title: string; description: string; data: unknown[]; actions?: React.ReactNode; children: React.ReactNode; className?: string }) { return <Card className={`overflow-hidden border-border/80 shadow-[0_12px_34px_-25px_rgba(15,23,42,0.35)] ${className}`}><CardHeader className="gap-3 border-b bg-muted/[0.18] pb-4 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="text-[15px]">{title}</CardTitle><CardDescription className="mt-1 text-xs">{description}</CardDescription></div>{actions && <div className="flex flex-wrap gap-2 sm:justify-end">{actions}</div>}</CardHeader><CardContent className="p-4 pt-5">{data.length ? children : <EmptyChart />}</CardContent></Card>; }
function StatCard({ label, value, hint, icon: Icon, accent }: { label: string; value: number; hint: string; icon: typeof Truck; accent: "blue" | "emerald" | "amber" | "rose" }) { const styles = { blue: "bg-blue-600 text-blue-600", emerald: "bg-emerald-600 text-emerald-600", amber: "bg-amber-500 text-amber-600", rose: "bg-rose-500 text-rose-600" }[accent].split(" "); return <Card className="relative overflow-hidden border-border/80 shadow-sm"><div className={`absolute right-0 top-0 h-full w-1 ${styles[0]}`} /><CardContent className="flex items-start justify-between p-5"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-0.04em]">{formatNumber.format(value)}</p><p className="mt-1.5 text-[11px] text-muted-foreground">{hint}</p></div><div className={`grid size-10 place-items-center rounded-xl ${styles[0]}/10`}><Icon className={`size-5 ${styles[1]}`} /></div></CardContent></Card>; }
function mergeRuptureSeries(items: ChartPoint[], vehicles: ChartPoint[]) { const labels = new Set([...items.map(point => point.label), ...vehicles.map(point => point.label)]); return Array.from(labels).sort((a, b) => a.localeCompare(b, "pt-BR", { numeric: true })).map(label => ({ label, itens: items.find(point => point.label === label)?.value ?? 0, veiculos: vehicles.find(point => point.label === label)?.value ?? 0 })); }

export default function ReceptionDashboard() {
  const [filters, setFilters] = useState<DashboardFilters>({});
  const [periodPreset, setPeriodPreset] = useState("all");
  const [macroCategory, setMacroCategory] = useState("all");
  const dashboard = trpc.logistics.reception.dashboard.useQuery(filters, { refetchOnWindowFocus: false });
  const data = dashboard.data;
  const ruptureData = data ? mergeRuptureSeries(data.ruptureItemsByDay, data.ruptureVehiclesByDay) : [];
  const macroPoints = useMemo(() => filterMacroCategoryByDay(data?.vehiclesByMacroCategoryAndDay ?? [], macroCategory), [data?.vehiclesByMacroCategoryAndDay, macroCategory]) as MacroCategoryDayPoint[];
  const macroCategories = useMemo(() => Array.from(new Set((data?.vehiclesByMacroCategoryAndDay ?? []).map(point => point.macroCategory))).sort(), [data?.vehiclesByMacroCategoryAndDay]);
  const macroChartData = useMemo(() => {
    const dates = new Map<string, Record<string, number | string>>();
    for (const point of macroPoints) dates.set(point.date, { ...(dates.get(point.date) ?? { date: point.date }), [point.macroCategory]: point.value });
    return Array.from(dates.values()).sort((a, b) => String(a.date).localeCompare(String(b.date), "pt-BR", { numeric: true }));
  }, [macroPoints]);
  const displayedMacros = macroCategory === "all" ? macroCategories : [macroCategory];

  function changePreset(value: string) { setPeriodPreset(value); if (value === "all") { setFilters({}); return; } if (value === "custom") return; setFilters(futurePeriodFromSelectedStart(filters.startDate, new Date(), value === "7" ? 7 : 30)); }
  function changeDate(field: "startDate" | "endDate", value: string) { setPeriodPreset("custom"); setFilters(previous => ({ ...previous, [field]: value || undefined })); }

  if (dashboard.isLoading) return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-32" />)}</div><div className="grid gap-5 lg:grid-cols-2">{Array.from({ length: 7 }).map((_, index) => <Skeleton key={index} className="h-[360px]" />)}</div></div>;
  if (dashboard.error) return <Card className="border-destructive/35 bg-destructive/[0.03]"><CardContent className="flex min-h-64 flex-col items-center justify-center p-8 text-center"><AlertTriangle className="mb-4 size-8 text-destructive" /><h2 className="text-lg font-semibold">Não foi possível carregar o recebimento</h2><p className="mt-2 max-w-lg text-sm text-muted-foreground">{dashboard.error.message}</p><Button className="mt-5" variant="outline" onClick={() => dashboard.refetch()}><RefreshCw className="mr-2 size-4" />Tentar novamente</Button></CardContent></Card>;
  const totals = data?.totals ?? { vehicles: 0, pallets: 0, ruptureItems: 0, ruptureVehicles: 0 };
  const days = data?.dateRange.daysInPeriod ?? 0;
  const averageHint = days === 1 ? "total do dia filtrado" : `média dos totais diários em ${days} dia(s)`;
  const dateTick = (label: string) => label;

  return <div className="space-y-6"><section className="relative overflow-hidden rounded-3xl border border-border/80 bg-card p-7 shadow-[0_16px_45px_-28px_rgba(15,23,42,0.32)] md:p-9"><div className="absolute -right-20 -top-20 size-72 rounded-full bg-blue-500/10 blur-3xl" /><div className="relative flex flex-col gap-6"><div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div className="max-w-2xl"><Badge variant="secondary" className="mb-4 bg-blue-500/10 text-[10px] font-bold uppercase tracking-[0.14em] text-blue-700 dark:text-blue-300">Operação de recebimento</Badge><h2 className="text-2xl font-semibold tracking-[-0.035em] md:text-3xl">Decisões guiadas pela programação.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Selecione manualmente qualquer período ou use faixas futuras. Todos os indicadores acompanham o filtro aplicado.</p></div><Button variant="outline" className="rounded-xl bg-card/70" disabled={dashboard.isFetching} onClick={() => dashboard.refetch()}>{dashboard.isFetching ? <RefreshCw className="mr-2 size-4 animate-spin" /> : <RefreshCw className="mr-2 size-4" />}Atualizar dados</Button></div><DashboardFilterControls filters={filters} periodPreset={periodPreset} onDateChange={changeDate} onPresetChange={changePreset} onReset={() => { setFilters({}); setPeriodPreset("all"); }} /></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Veículos programados" value={totals.vehicles} hint="senhas distintas no filtro" icon={Truck} accent="blue" /><StatCard label="Paletes previstos" value={totals.pallets} hint="total da agenda filtrada" icon={Boxes} accent="emerald" /><StatCard label="Itens em ruptura" value={totals.ruptureItems} hint="ocorrências no filtro" icon={AlertTriangle} accent="amber" /><StatCard label="Veículos em ruptura" value={totals.ruptureVehicles} hint="senhas impactadas" icon={PackageCheck} accent="rose" /></div>
    <section className="grid gap-5 xl:grid-cols-2"><ChartCard title="Veículos por dia" description="Senhas distintas por data. Todas as datas do intervalo permanecem visíveis." data={data?.vehiclesByDay ?? []}><div className="overflow-x-auto"><div className="min-w-[760px]"><ResponsiveContainer width="100%" height={310}><BarChart data={data?.vehiclesByDay} margin={{ top: 20, right: 10, left: -14, bottom: 55 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis dataKey="label" interval={0} tickFormatter={dateTick} angle={-45} textAnchor="end" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={32} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: number) => [formatNumber.format(value), "Veículos"]} /><Bar dataKey="value" name="Veículos" fill="#2563eb" radius={[7, 7, 0, 0]}><LabelList dataKey="value" position="top" style={{ fontSize: 10, fill: "currentColor" }} /></Bar></BarChart></ResponsiveContainer></div></div></ChartCard>
      <ChartCard title="Veículos por categoria macro e dia" description="A categoria macro usa as três primeiras letras da categoria original, segmentada por data." data={macroChartData} actions={<DashboardSelect ariaLabel="Filtrar categoria macro" value={macroCategory} onChange={setMacroCategory}><option value="all">Todas as macros</option>{macroCategories.map(item => <option key={item} value={item}>{item}</option>)}</DashboardSelect>}><div className="overflow-x-auto"><div className="min-w-[760px]"><ResponsiveContainer width="100%" height={310}><BarChart data={macroChartData} margin={{ top: 20, right: 10, left: -14, bottom: 55 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis dataKey="date" interval={0} angle={-45} textAnchor="end" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={32} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: number) => [formatNumber.format(value), "Veículos"]} /><Legend wrapperStyle={{ fontSize: 11 }} />{displayedMacros.map((macro, index) => <Bar key={macro} dataKey={macro} name={macro} fill={seriesColors[index % seriesColors.length]} radius={[5, 5, 0, 0]}><LabelList dataKey={macro} position="top" style={{ fontSize: 9, fill: "currentColor" }} /></Bar>)}</BarChart></ResponsiveContainer></div></div></ChartCard>
      <ChartCard title="Veículos por hora" description={`${averageHint}. Cada dia é totalizado por hora antes do cálculo da média.`} data={data?.vehiclesByHour ?? []}><ResponsiveContainer width="100%" height={280}><BarChart data={data?.vehiclesByHour} margin={{ top: 20, right: 10, left: -14 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis dataKey="label" interval={0} tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={32} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: number) => [formatNumber.format(value), "Média de veículos"]} /><Bar dataKey="value" name="Média de veículos" fill="#0ea5e9" radius={[7, 7, 0, 0]}><LabelList dataKey="value" position="top" style={{ fontSize: 10, fill: "currentColor" }} /></Bar></BarChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Paletes por hora" description={`${averageHint}. Cada dia é totalizado por hora antes do cálculo da média.`} data={data?.palletsByHour ?? []}><ResponsiveContainer width="100%" height={280}><BarChart data={data?.palletsByHour} margin={{ top: 20, right: 10, left: -14 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis dataKey="label" interval={0} tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={32} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: number) => [formatNumber.format(value), "Média de paletes"]} /><Bar dataKey="value" name="Média de paletes" fill="#14b8a6" radius={[7, 7, 0, 0]}><LabelList dataKey="value" position="top" style={{ fontSize: 10, fill: "currentColor" }} /></Bar></BarChart></ResponsiveContainer></ChartCard></section>
    <section className="grid gap-5 xl:grid-cols-2"><ChartCard title="Paletes por turno" description="1º turno: 06:00–13:59 · 2º: 14:00–21:59 · 3º: 22:00–05:59." data={data?.palletsByShift ?? []}><ResponsiveContainer width="100%" height={270}><BarChart data={data?.palletsByShift}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={38} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: number) => [formatNumber.format(value), "Paletes"]} /><Bar dataKey="value" name="Paletes" fill="#10b981" radius={[7, 7, 0, 0]}><LabelList dataKey="value" position="top" style={{ fontSize: 11, fill: "currentColor" }} /></Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Paletes por dia" description="Previsão total por data no padrão dd/mm/aaaa." data={data?.palletsByDay ?? []}><div className="overflow-x-auto"><div className="min-w-[760px]"><ResponsiveContainer width="100%" height={310}><BarChart data={data?.palletsByDay} margin={{ top: 20, right: 10, left: -14, bottom: 55 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis dataKey="label" interval={0} angle={-45} textAnchor="end" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={38} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: number) => [formatNumber.format(value), "Paletes"]} /><Bar dataKey="value" name="Paletes" fill="#2563eb" radius={[7, 7, 0, 0]}><LabelList dataKey="value" position="top" style={{ fontSize: 10, fill: "currentColor" }} /></Bar></BarChart></ResponsiveContainer></div></div></ChartCard><ChartCard title="Paletes por categoria" description="Categorias com maior previsão de descarga no filtro atual." data={data?.palletsByCategory ?? []}><ResponsiveContainer width="100%" height={270}><BarChart data={data?.palletsByCategory} layout="vertical" margin={{ left: 16 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis type="number" allowDecimals={false} tickLine={false} axisLine={false} tick={{ fontSize: 11 }} /><YAxis dataKey="label" type="category" width={112} tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><Tooltip formatter={(value: number) => [formatNumber.format(value), "Paletes"]} /><Bar dataKey="value" name="Paletes" fill="#f59e0b" radius={[0, 7, 7, 0]}><LabelList dataKey="value" position="right" style={{ fontSize: 10, fill: "currentColor" }} /></Bar></BarChart></ResponsiveContainer></ChartCard></section>
    <ChartCard title="Visão de ruptura por dia" description="Itens em ruptura e veículos impactados por data de agenda." data={ruptureData}><div className="overflow-x-auto"><div className="min-w-[760px]"><ResponsiveContainer width="100%" height={315}><BarChart data={ruptureData} margin={{ top: 20, right: 10, left: -14, bottom: 55 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><XAxis dataKey="label" interval={0} angle={-45} textAnchor="end" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={32} tick={{ fontSize: 11 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="itens" name="Itens em ruptura" fill="#f59e0b" radius={[5, 5, 0, 0]}><LabelList dataKey="itens" position="top" style={{ fontSize: 10, fill: "currentColor" }} /></Bar><Bar dataKey="veiculos" name="Veículos em ruptura" fill="#e11d48" radius={[5, 5, 0, 0]}><LabelList dataKey="veiculos" position="top" style={{ fontSize: 10, fill: "currentColor" }} /></Bar></BarChart></ResponsiveContainer></div></div></ChartCard>
  </div>;
}
